"""create initial tables

Revision ID: 2efc3cfa4a32
Revises: 
Create Date: 2026-09-01 21:42:16.277542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2efc3cfa4a32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server_settings.server_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patreon_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('tier_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server_settings.server_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tier_id'], ['tier_roles.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patreon_users')
    op.drop_table('tier_roles')
    # ### end Alembic commands ###
