"""create initial tables

Revision ID: 5cb483379e02
Revises: 
Create Date: 2026-09-01 20:13:54.243736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb483379e02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_settings',
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.create_table('tier_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server_settings.server_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patreon_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('tier_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server_settings.server_id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['tier_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patreon_users')
    op.drop_table('tier_roles')
    op.drop_table('server_settings')
    # ### end Alembic commands ###
