"""create initial tables

Revision ID: 7e6a1cdf65aa
Revises: 
Create Date: 2026-08-18 20:22:06.166995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6a1cdf65aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('create_channel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_create_channel_server_id'), 'create_channel', ['server_id'], unique=False)
    op.create_table('server_settings',
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.create_table('voice_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_channels_server_id'), 'voice_channels', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_channels_server_id'), table_name='voice_channels')
    op.drop_table('voice_channels')
    op.drop_table('server_settings')
    op.drop_index(op.f('ix_create_channel_server_id'), table_name='create_channel')
    op.drop_table('create_channel')
    # ### end Alembic commands ###
